#!/bin/bash
# Bashrc SSH-xpra wrapper | Spencer Tipping
# Licensed under the terms of the MIT source code license

# Source this in your bashrc to automatically reroute non-X11 terminal sessions
# into the same persistent xpra display.

if [[ -z "$DISPLAY" && -x /usr/bin/xpra ]]; then
  XPRA_DISPLAY=${XPRA_DISPLAY:-:100}
  xpra start $XPRA_DISPLAY ${XPRA_SERVER_OPTIONS:---sharing} >& /dev/null \
    && echo "Using xpra display $XPRA_DISPLAY"
  export DISPLAY=$XPRA_DISPLAY
fi
