#!/bin/bash
# Bashrc SSH-tmux wrapper | Spencer Tipping
# Licensed under the terms of the MIT source code license

# Source this just after the PS1-check to enable auto-tmuxing of your SSH
# sessions. See https://github.com/spencertipping/bashrc-tmux for usage
# information.

if [[ -z "$TMUX" && -n "$SSH_CONNECTION" ]] && which tmux >& /dev/null; then
  if ! tmux ls -F '#{session_name}' | grep "^ssh-$USER$" > /dev/null; then
    tmux new-session -s ssh-$USER \; detach
  fi

  # Allocating a session ID.
  # There are two possibilities here. First, we could have a list of session
  # IDs that is densely packed; e.g. [0, 1, 2, 3, 4]. In this case, we want to
  # allocate 5.
  #
  # If, on the other hand, there is a gap, then it becomes unsafe to just use
  # #sessions as the new ID. So instead, we search through the list to see if
  # the difference between any pair is greater than one. (e.g. for [0, 1, 3, 5]
  # we would use 2)

  session=($(tmux ls -F '#{session_name}' \
             | grep "^ssh-$USER-\d+$" \
             | sed "s/^ssh-$USER-//" \
             | sort -n))
  session_index=${#sessions[@]}

  for ((i = 1; i < ${#sessions[@]}; ++i)); do
    if (( ${sessions[$i]} - ${sessions[$(($i - 1))]} > 1 )); then
      session_index=$((${sessions[$i]} + 1))
      break
    fi
  done

  exec tmux new-session -s ssh-$USER-$session_index -t ssh-$USER
fi
